# Generated by Django 6.1 on 2026-08-22 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0002_tutor_skillswaprequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileskill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skillswaprequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skillswaprequest',
            name='skill_to_teach',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='specialization',
        ),
        migrations.AddField(
            model_name='tutor',
            name='expertise',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillapp.profile'),
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillapp.skill'),
        ),
        migrations.AlterField(
            model_name='skillswaprequest',
            name='skill_to_learn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillapp.skill'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
