# Generated by Django 6.1 on 2026-09-01 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0004_mocktest_certificate_testattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='skillapp.profile'),
        ),
    ]
