# Generated by Django 6.1 on 2026-09-05 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0006_swapmeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='marks_per_question',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='show_result_immediately',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_tests', to='skillapp.skill'),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='total_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20),
        ),
    ]
