# Generated by Django 6.1 on 2026-09-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0007_mocktest_difficulty_mocktest_marks_per_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
