# Generated by Django 6.1 on 2026-09-05 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0008_certificate_payment_status_certificate_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_request', to='skillapp.testattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='skillapp.profile')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='skillapp.mocktest')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='skillapp.tutor')),
            ],
        ),
    ]
