# Generated by Django 6.1 on 2026-09-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0009_certificaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved by Tutor'), ('rejected', 'Rejected'), ('paid', 'Payment Completed'), ('completed', 'Certificate Issued')], default='pending', max_length=20),
        ),
    ]
