# Generated by Django 6.1 on 2026-09-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0010_alter_certificaterequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='payment_amount',
            field=models.IntegerField(default=199),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
